### ISSUE TITLE
Add sent emails grid

### ISSUE THREAD

**Issue by roma84** [tmhub/email#9]

**Comment by CemeeII** [comment]
This would be very usefull. So you can check the mails that have been sent by Magento.
Aschroder SMTP Pro extension has this feature.

**Comment by 0m3r** [comment]
![2018-04-02 17-09-19](https://user-images.githubusercontent.com/412612/38199207-99d442e6-3698-11e8-80a4-9eaaf27badd0.png)

**Comment by 0m3r** [comment]
![2018-04-02 17-10-16](https://user-images.githubusercontent.com/412612/38199247-bd34e1e6-3698-11e8-845b-c84bbed9d486.png)
